### ISSUE TITLE
Program to change and save registries

### ISSUE THREAD

**Issue by RibeiroSantos** [raduprv/esp32-cam_ov2640-timelapse#2]
Hi, is it possible to send me your program?
Thanks a lot

**Comment by raduprv** [comment]
Ok, I sent you the fuzzer.
Please take a look at it, and if you have any questions feel free to drop me a line.
To use it, just upload it on the ESP32 cam, put a card in it, and let it run. It will take a picture every ~20 seconds or so (it is configurable). The filename is like so: sprintf(path,"/%i_%02x_%02x_%i_1.jpg%s",bank,reg,value,millis(),fb? "" : "bad");
so bank_reg_value_time.jpg Bad files are saved with a different extensions.

As you can see, there is some code to upload the images to a ftp server, but it is disabled. It doesn't work well on my esp32 cam (there are some wifi problems).

**Comment by FBMinis** [comment]
Can you share this fuzzer with me? I've been playing with the camera again and would like to try to understand more about it.
