### ISSUE TITLE
Ask adavice for modifying OV2640 register

### ISSUE THREAD

**Issue by Dwight-Choi** [raduprv/esp32-cam_ov2640-timelapse#8]
Hi, thank you for your effort to optimize the register values for image quality. It's awesome. 
I want to ask you for some advice to modify the register of OV2640. For my project, I need to get the Bayer raw data from the image sensor of OV2640 with esp32-cam, and the raw image is not supported by the ESP32-CAM library. Here is my inquiry to the contributor of the esp32 camera library. (https://github.com/espressif/esp32-camera/issues/464#issuecomment-1284807766)
The thing is I don't have any experience or background with this register-related code, so I have no idea how to start this task. Could you give me any idea to deal with this?

**Comment by raduprv** [comment]
Hi
I didn't touch this project in a long while, and never worked with the RAW, so I am afraid I can't help you.

**Comment by Dwight-Choi** [comment]
Thank you for your reply though. Hope you have a great day!
